### ISSUE TITLE
No tags on Docker Hub since SDK v183.0.0

### ISSUE THREAD

**Issue by joaocabrita** [GoogleCloudPlatform/cloud-sdk-docker#124]
The latest tag on Docker Hub is 183.0.0
There are more recent builds but they all use `latest`, which I'd like to avoid because it's a moving target.

**Comment by ahmetb** [comment]
Normally we push tags, however it looks like coincidentally all :VERSION builds have failed on docker hub due to some weird error: https://hub.docker.com/r/google/cloud-sdk/builds/bdgquwqeynanyr6he8fastu/ 

> Build failed: Get https://registry-1.docker.io/v2/library/docker/manifests/17.09.0-ce: unauthorized: incorrect username or password

It looks like Docker Hub is failing to pull images from its own public registry.

@salrashid123 do you have access to our Docker Hub account to perhaps rebuild these tags (the only other option I have is to re-tag the release here, which is less preferable).

**Comment by salrashid123** [comment]
i just retriggered a build but the way the dockerhub build rules are setup, it'll just use the git tag as ```:version```  (i don't see anywhere i can 'trigger' that as a tag)

![image](https://user-images.githubusercontent.com/11149054/36685802-4e1ffe1a-1ad9-11e8-81e8-f4324095b12d.png)

@ahmetb   i think we need to tag and push to get ```:version```   
btw, the latest is ```:190.0.1``` so we can use that after backfill

**Comment by ahmetb** [comment]
I just pushed 190.0.1 tag, let's see if this builds.

We've been seeing a lot of failed builds about tags due to random errors. I just got this response from Docker Hub  https://twitter.com/Docker/status/968183418818359296 although I'm not satisfied it's the actual reason it failed.

If this fails again, we should consider switching to another registry, like GCR.io perhaps.

**Comment by salrashid123** [comment]
ok, they all succeeded now

```bash
$ docker run -ti  google/cloud-sdk:190.0.1 gcloud version
Google Cloud SDK 190.0.1
alpha 2018.02.22
app-engine-go 
app-engine-java 1.9.62
app-engine-python 1.9.67
beta 2018.02.22
bigtable 
bq 2.0.29
cbt 
cloud-datastore-emulator 1.4.1
core 2018.02.22
datalab 20180213
gsutil 4.28
pubsub-emulator 2018.02.22
```

same with ```docker run -ti  google/cloud-sdk:latest gcloud version```
