### ISSUE TITLE
Remove sid / unstable from the package sources from the debian images

### ISSUE THREAD

**Issue by b7kich** [GoogleCloudPlatform/cloud-sdk-docker#203]
Including sid / unstable is an AntiPattern known as ["FrankenDebian"](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian). It leads to a number of upgrade / installation issues like #201. The root cause for this issue seems to be the [lack of a stable version of Oracle's "openjdk-8-jdk" package](https://stackoverflow.com/questions/57031649/how-to-install-openjdk-8-jdk-on-debian-10-buster) for debian distributions like buster. 
```
$ docker run -it --rm google/cloud-sdk:290.0.1 apt policy  | grep -A 2 sid/
 500 http://deb.debian.org/debian sid/main amd64 Packages
     release o=Debian,a=unstable,n=sid,l=Debian,c=main,b=amd64
     origin deb.debian.org
```

**Comment by YPCrumble** [comment]
I would love to see this implemented! This seems to be the solution of the root cause of #193, #200 and #201. My team is stuck on release 276 because of sid.

Thank you for raising this - I'd be happy to help implement a fix or at a minimum test the fix.

**Comment by willfaris** [comment]
Waiting for some emulator components to declare support for Java 11 before removing sid.

**Comment by willfaris** [comment]
If you don't want to use an image that has 'sid' added then you can try and use the tag 'google/cloud-sdk:debian_component_based'.

**Comment by YPCrumble** [comment]
@willfaris we just tried using `google/cloud-sdk:debian_component_based` but it's very far from a plug and play solution - we couldn't realistically get it to work without significant work.

The fact is that while using `sid` for us the build continues to be broken since release 276. Because removing sid would also solve #193 as well as the other various issues I mentioned above, do you think it's worth simply removing it? It feels like it is breaking a lot and I'm not sure what it's solving.

**Comment by willfaris** [comment]
sid _was_ allowing openjdk 8 to be installed, but that broke very recently, so for now sid is removed from the main image.
