### ISSUE TITLE
'gcloud config set project' returns warning.

### ISSUE THREAD

**Issue by ahmetgeymen** [GoogleCloudPlatform/cloud-sdk-docker#222]
image: google/cloud-sdk:alpine

`gcloud config set project $PROJECT_ID`

When we run script above on Bitbucket Pipelines, it shows message below

> Updated property [core/project].
> WARNING: You do not appear to have access to project [_project_id_] or it does not exist.

We use the service-account key that is generated for the project. Similar question is asked in [here](https://stackoverflow.com/questions/58733523/google-cloud-platform-warning-you-do-not-appear-to-have-access-to-project-pro)

**Comment by willfaris** [comment]
That warning is because the SA does not have read access to the project, the warning exists to catch typos when interactive users mistype the project id when running `gcloud config set project PROJECTID`.

If you really want to remove the WARNING you can do something like

`gcloud projects  add-iam-policy-binding PROJECTID --member "serviceAccount:SERVICE_ACCOUNT_EMAIL" --role "roles/viewer"`

**Comment by vilasj** [comment]
Closing issue, please re-open if the previous comment does not resolve/clarify the problem.
