### ISSUE TITLE
314.0.0 PubSub emulator no longer installed properly

### ISSUE THREAD

**Issue by AdamMagaluk** [GoogleCloudPlatform/cloud-sdk-docker#225]
With release 314.0.0 the pubsub emulator fails to start with the message saying the component is not installed. 313.0.* images and before work ok.

```
λ: docker run -ti google/cloud-sdk:314.0.0
Unable to find image 'google/cloud-sdk:314.0.0' locally
314.0.0: Pulling from google/cloud-sdk
Digest: sha256:b3c9c664ca7ec1728a533f1be3969e92ab1c7e1bb2ac10813a1c620f4248e17c
Status: Downloaded newer image for google/cloud-sdk:314.0.0
root@ab96c319d551:/# gcloud beta emulators pubsub start
You need the [pubsub-emulator] component to use the Google Cloud
Pub/Sub emulator.
ERROR: (gcloud.beta.emulators.pubsub.start)
You cannot perform this action because the Cloud SDK component manager
is disabled for this installation. You can run the following command
to achieve the same result for this installation:

sudo apt-get install google-cloud-sdk-pubsub-emulator
```

**Comment by willfaris** [comment]
Because of an issue with installing openjdk8, the pubsub emulator component had to be removed from the 314.0.0 image.

See 

https://github.com/GoogleCloudPlatform/cloud-sdk-docker/commit/b75f3f692e7eb9d496e3cb8e46f68ec48f5a63e9#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

Please use the google/cloud-sdk:313.0.0 tag for now.

We expect pubsub emulator and (google-cloud-sdk-app-engine-java) to be back in the image with the 315.0.0.0 release scheduled on Oct 20, 2020.

**Comment by sjudeng** [comment]
Is it worth keeping this issue open until it's fixed with the next release, to help with visibility and reduce duplicate issues?

**Comment by vilasj** [comment]
Good idea, thanks.

**Comment by willfaris** [comment]
PubSub emulator is back in the 315.0.0 image, it now works with Java 11.
