### ISSUE TITLE
google-cloud-sdk  multi-arch docker image for intel ARM64

### ISSUE THREAD

**Issue by clouddev-code** [GoogleCloudPlatform/cloud-sdk-docker#280]
GKE support ARM64 architecure.
https://cloud.google.com/blog/products/compute/tau-t2a-is-first-compute-engine-vm-on-an-arm-chip?s=09

The following google-cloud-sdk docker image is only intel architecture.
support multi-arch docker image for intel ARM64

docerhub

https://hub.docker.com/r/google/cloud-sdk/

gcr.io

https://console.cloud.google.com/gcr/images/google.com:cloudsdktool/global/cloud-sdk

**Comment by billchurch** [comment]
This would also allow supporting of ARM based Apple M1/M2 processors

**Comment by billchurch** [comment]
While I see #269, #232, and #204 listed as closed, docker hub still reports OS/ARCH as `linux/amd64` for all the most recent tags.

https://hub.docker.com/r/google/cloud-sdk/tags

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/1668075/186628753-f3f3bcd4-d8af-4ca3-a1a4-665e09a355e5.png">

There doesn't seem to be a way to reference this which will pull in the arm64 versions.

**Comment by cloudsdkdocker** [comment]
Hi billchurch,

The cloud cli docker image is currently hosted on GCR: https://pantheon.corp.google.com/gcr/images/google.com:cloudsdktool/GLOBAL/google-cloud-cli

We've continued to update images that existed on dockerhub prior to us migrating to GCR in order to prevent breakages for existing users, however we will eventually stop updating even those image once we decide when to EOL them.

If you'd like to use multiarch images please pull them from GCR.

**Comment by jochenschneider** [comment]
Only cloud-cli images seem to have arm64 support, not cloud-sdk images.
