### ISSUE TITLE
google-cloud-cli:416.0.0 removed in Container Registry

### ISSUE THREAD

**Issue by bobidle** [GoogleCloudPlatform/cloud-sdk-docker#308]
The latest version of the google-cloud-cli image v416.0.0 was shortly available in the Container Registry.
https://console.cloud.google.com/gcr/images/google.com:cloudsdktool/GLOBAL/google-cloud-cli

But now the latest image is v415.0.0 again, why was the new version removed?

Docker Hub still provides v416.0.0
https://hub.docker.com/r/google/cloud-sdk/tags

**Comment by cloudsdkdocker** [comment]
Hi Bob,

The Cloud CLI Team recently migrated our container hosting from Container Registry to Artifact Registry. The AR team developed a redirection service to direct all GCR traffic to AR whicih we enabled. They discovered late last night that that redirection broke customers using VPC Service Controls and rolled back the redirection service as a mitigation. One impact of this is that the most recent release was only uploaded to AR and not GCR, so customers were suddenly pulling the previous release rather than the most recent.

I've already kicked off the build to add 416.0.0 to container registry, they should be available within the hour.
