### ISSUE TITLE
multi-arch images?

### ISSUE THREAD

**Issue by BenTheElder** [GoogleCloudPlatform/cloud-sdk-docker#317]
I see past discussion here https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/280#issuecomment-1273615171

but AFAICT none of the recent images for cloud-sdk are multi-arch still, and most architectures are unavailable in the google-cloud-cli image.

xref: https://github.com/kubernetes/cloud-provider-gcp/issues/433

**Comment by keeth** [comment]
another vote for this.  we need `arm64`.  thanks!!

**Comment by keeth** [comment]
Ok, if it helps anyone, this is how I built a multi-arch BigTable emulator image:

https://gist.github.com/keeth/cf537eb3421bd73a3184a604d287aa6a

Unfortunately I had to start with a python base image to make it work, because the Cloud CLI image only allows components to be installed via APT, but there are no `arm64` packages available.

It's too bad that arm64 support is broken, given its increasing popularity in the cloud and on desktop.

**Comment by cloudsdkdocker** [comment]
Hi Keeth,

If you'd like to install components outside of apt you can use the :debian_component_based image.

To clarify further about why we can't release arm support for the :latest tag, it's because multiple of the packaged components included in the image don't support arm. For us to enable arm support for these specific images, we'd have to remove these tools which would be breaking for a large # of customers using them.

**Comment by BenTheElder** [comment]
> For us to enable arm support for these specific images, we'd have to remove these tools which would be breaking for a large # of customers using them.

This seems like a false dichotomy, can we not work with these other components to build multi-arch as well instead of removing them?

**Comment by cloudsdkdocker** [comment]
We have been pushing these component owners to release arm supported versions of their packages for some time. Many of the packaged components distributed by the Cloud CLI have unclear or reluctant ownership due to their age and getting lost amidst a large number of reorganizations. Until such time that they either go through a full deprecation process or decide to release arm64 versions of their packages, the only path to releasing an arm image for the :latest tag would be to remove the packages, which would be a breaking change to its current users.

Given all other tags support arm64, and that the :slim image is effectively (almost) the same image as :latest without the packages which don't support arm, we feel that we're not limiting users. We're also deliberating releasing a super slim image which will be the Cloud CLI with no extra components which users can layer or modify as they see fit.

One thing that the CLI team does not plan to support is images for every possible combination of the CLI and its packaged components as we feel this would become unmaintainable due to every possible user's unique needs and desires, particularly when image layering and modification are very straightforward, and especially with how simple the dockerfiles for the 5 existing images are to replicate.

If the Cloud CLI Team finds itself with the ability to compel these packaged component owners to enable arm64 support or properly deprecate, or we find the bandwidth do so ourselves we will do so ASAP

**Comment by cloudsdkdocker** [comment]
FYI I've created an internal tracking bug to renew the push to release arm64 versions of these packaged components from our partner teams.
