### ISSUE TITLE
APT repository changed Origin to cloud-sdk-bullseye

### ISSUE THREAD

**Issue by valkum** [GoogleCloudPlatform/cloud-sdk-docker#373]
A Dockerfile with
```
FROM gcr.io/google.com/cloudsdktool/cloud-sdk:slim

RUN apt-get update && apt-get -yq upgrade && apt-get -yq install gnupg openssh-client && apt-get clean
```
currently fails with the following error message:
```
Repository 'https://packages.cloud.google.com/apt cloud-sdk-bookworm InRelease' changed its 'Origin' value from 'cloud-sdk-bookworm' to 'cloud-sdk-bullseye'
E: Repository 'https://packages.cloud.google.com/apt cloud-sdk-bookworm InRelease' changed its 'Label' value from 'cloud-sdk-bookworm' to 'cloud-sdk-bullseye'
```
Downgrading to `gcr.io/google.com/cloudsdktool/cloud-sdk:465.0.0-slim` fixes it for now.

**Comment by cloudsdkdocker** [comment]
Hi Valkum,

I'm unable to replicate this issue pulling the :slim tag. 

Yesterday we had a similar issue with full project names being prepended to repository origins due to a bug in a redirection service but that's been resolved since ~ yesterday noon.

Can you confirm to me that this issue is still occurring if you pull the most recent cloud-sdk:slim image and run the command?

**Comment by valkum** [comment]
We saw the error approx. 16 hours ago. It seems to be fixed with the recently pushed 466 from 4 hours ago. Sorry for the noise.
