### ISSUE TITLE
any alpine version?

### ISSUE THREAD

**Issue by medyagh** [GoogleCloudPlatform/cloud-sdk-docker#54]
is there an alpline version ?

**Comment by sbani** [comment]
hi @medyagh,

there seems to be no official version. Nevertheless you can find many of those at the docker hub: 

https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=alpine+gcloud&starCount=0

or

https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=google+cloud+sdk&starCount=0

The reason why I'm watching this github repo is that I created one by myself:
https://hub.docker.com/r/sbani/google-gloud-sdk/
_Disclaimer: I install and run the tools as root, because I use it within my Continuous Integration stack where I need the privileges. You're welcome to fork, copy and contribute_

**Comment by salrashid123** [comment]
hi-

if you wanted to generate an alpine package itself, see

* [https://github.com/salrashid123/cloud-sdk-docker#alpine-package](https://github.com/salrashid123/cloud-sdk-docker#alpine-package)

(note, its pinned to gcloud sdk 147...you can update it pretty easily; instructions on that page itself)

the repo shows standard baseline images on centos,ubuntu with the plain sdk install (+some usecases derived from this repo).

the sdk's 147 pinned version (at the moment)...the auto-generated images are here
[https://hub.docker.com/r/salrashid123/cloud-sdk-docker/tags/](https://hub.docker.com/r/salrashid123/cloud-sdk-docker/tags/)

note, the cloud sdk here is derived from 
```
FROM gcr.io/google_appengine/base
```

i'l submit an issue to update the baseline to something generic (eg ubuntu or alpine)...that'll also trigger the dockerhub image update too.

**Comment by ahmetb** [comment]
We now have an alpine version #68 .
