### ISSUE TITLE
kubectl no longer preinstalled

### ISSUE THREAD

**Issue by max-vogler** [GoogleCloudPlatform/cloud-sdk-docker#75]
Recent changes seem to no longer include `kubectl`. This breaks our CI which relied on `kubectl` being present:

```
docker run --rm -it google/cloud-sdk
Unable to find image 'google/cloud-sdk:latest' locally
latest: Pulling from google/cloud-sdk
6f821164d5b7: Pull complete 
5d7c6e9ed739: Pull complete 
Digest: sha256:e9e9b8d6c760a4fbfe28a17606b566f4522b5d9226cca9cbcde157fa82d0154f
Status: Downloaded newer image for google/cloud-sdk:latest
/ # kubectl
/bin/sh: kubectl: not found
```

```
/ # gcloud components list | grep kubectl

Your current Cloud SDK version is: 159.0.0
The latest available version is: 159.0.0

| Not Installed | kubectl | ...
```

It seems like others have the same problem as well (https://github.com/GoogleCloudPlatform/cloud-sdk-docker/commit/081fa06bbfc65a1b72baae31131fb7d53ba74ee0#commitcomment-22619593). The same behavior occurs for older `gcloud` versions (I built images using `CLOUD_SDK_VERSION` `150.0.0` and `155.0.0` exemplarily).

Is this intended behavior or will this be fixed in a future version?

**Comment by max-vogler** [comment]
BTW, a temporary fix is to prepend your commands with
```
gcloud components install kubectl -q --no-user-output-enabled
```

**Comment by rscorer** [comment]
Would be nice to have this fixed :) Awkward to modify all our build scripts...

**Comment by MaxWinterstein** [comment]
thx name-buddy!  
I can confirm this works fine for me.  
I was going to build the old version myself and push it to my registry. But this is way quicker.

There is really a huge need for tags here...

**Comment by aisrael** [comment]
Yeah discovered the workaround ourselves, +1 to tags (isn't it "best practice"?)

**Comment by ahmetb** [comment]
Sorry for the breaking change, we just redid pretty much everything from scratch. This image didn't have tags before and we will be tagging the versions going forward. After a while, you can pin to a tag.

It'll take some time we fix tag the images on Docker Hub etc. I am not sure we will add additional components like kubectl in the image (mostly due to size reasons, and once we install _some_ additional components, it's not clear why others are not installed).

I would recommend people to follow @max-vogler’s suggestion of creating another image based on gcloud image and installing kubectl yourself.

**Comment by ahmetb** [comment]
That said, we may have an image with _all_ the additional components installed. This would make the image probably a few times larger than it is in size today. I am not sure if that is desirable but I don't think we'll be maintaining a kubectl flavor of the image.

**Comment by punitag** [comment]
We saw the same issue - created this image - https://hub.docker.com/r/punitag/gcloud-sdk-kubectl/
