### ISSUE TITLE
Moving To Alpine and Back to Jessie?

### ISSUE THREAD

**Issue by kri5** [GoogleCloudPlatform/cloud-sdk-docker#80]
A Few days ago, you made the switch to alpine linux as a base image, as it was notified on the docker hub. And now you switched back without noticing anyone to alpine?

And the alpine image isn't pushed to the registry.

we can clearly see the problem by looking at the Dockerfile from here https://hub.docker.com/r/google/cloud-sdk/builds/buybneabmhnqd2stdafxhgv/ and here https://hub.docker.com/r/google/cloud-sdk/builds/buybneabmhnqd2stdafxhgv/

Is this expected?

**Comment by ahmetb** [comment]
Yes. After redoing the image we thought a :latest that's alpine based an no components pre-installed would be what people need. This has broken many people and turns out many people use additional components.

Therefore we rolled out #78 to address #74. The `:latest` (and `:VERSION`) is now debian-based and has all additional components pre-installed (it's a large image). We don't have a tag for the Alpine now, however `:slim` tag should be small enough. We are hoping to move `:slim` to alpine once we can confirm it works correctly.

**Comment by kri5** [comment]
Well it worked for me, i made changes to adapt to alpine based image, and you do not even provide a different tag for this alpine based image. This is no way of doing releases.

**Comment by ahmetb** [comment]
Sorry about breaking you. Basically the repo has been unmaintained for more than a year and there was no tags at all, we started changing stuff and people got broken. They gave feedback that we addressed within first 24 hours.

We expect things to get more stable soon.

If we now provide an `:alpine` tag and then move the `:slim` to use the Alpine Dockerfile, we will have two tags doing the same thing. In that case we would delete `:alpine` at some point, which would break you again. If you have any suggestions, let us know.

**Comment by kri5** [comment]
You will anyway break people using the :slim image, because people do rely on the base system they are on.

**Comment by kri5** [comment]
It's now too late to do things properly, but you shouldn't have release a new `:slim` tag that will break at some point because the base system will not be the same.

**Comment by ahmetb** [comment]
@kri5 you can use a version tag to avoid such breaking changes. If you pin your base image to `:159.0.0-slim` today, when we change slim to use Alpine, we will not be updating the versioned image. However, if you stay on `:slim` latest image, the base OS may change under you. Does this sound reasonable?
