### ISSUE TITLE
Cannot install components via gcloud on newest build anymore (159.0.0, latest)

### ISSUE THREAD

**Issue by asarturas** [GoogleCloudPlatform/cloud-sdk-docker#81]
```
% docker run --rm -it google/cloud-sdk:159.0.0-slim /bin/bash
root@59f492e3dbcf:/# gcloud components install kubectl
You cannot perform this action because this Cloud SDK installation is
managed by an external package manager.  If you would like to get the
latest version, please see our main download page at:

https://cloud.google.com/sdk/

ERROR: (gcloud.components.install) The component manager is disabled for this installation
```

used to work on previous version (now named legacy).

Can use apt-get directly for kubectl of course, but it's a bit odd, given this is the official image.

**Comment by ahmetb** [comment]
@salrashid123 is this because the `-slim` image is Debian-based and things are installed via apt? If that's the case, maybe we should follow one of these following routes:

- Release also an `:alpine` tag, where this command would work.
- Provide documentation in README in a "How to install additional components" and list appropriate commands for debian (apt-get) and alpine (gcloud components install).

@asarturas in your case, `apt-get install kubectl` should work as listed here: https://cloud.google.com/sdk/downloads#apt-get

**Comment by asarturas** [comment]
@ahmetb just to clarify, this issue can be reproduced in non slim version as well:
```
docker run --rm -it google/cloud-sdk:159.0.0 /bin/bash
root@902bf762c049:/# gcloud components install kubectl
You cannot perform this action because this Cloud SDK installation is
managed by an external package manager.  If you would like to get the
latest version, please see our main download page at:

https://cloud.google.com/sdk/

ERROR: (gcloud.components.install) The component manager is disabled for this installation
```

**Comment by ahmetb** [comment]
> this issue can be reproduced in non slim version as well

This is because the non-slim version is Debian-based, too (see README). The non-slim version is very large in size, but it has kubectl preinstalled. 

Closing this issue as it is resolved for you.

**Comment by asarturas** [comment]
ah, cool, didn't realise. It's good that there was tagging introduced now, thanks.
